# Generated by Django 5.2 on 2025-09-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemType',
            new_name='VideoType',
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
                ('VideoType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modrator.videotype')),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modrator.category')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modrator.series')),
            ],
        ),
        migrations.DeleteModel(
            name='watchedItem',
        ),
    ]
