# Generated by Django 5.2 on 2025-09-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0002_rename_itemtype_videotype_videoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotype',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
