# Generated by Django 5.2 on 2025-09-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0003_category_quantity_videotype_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
