# Generated by Django 5.2 on 2025-09-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0005_alter_videotype_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotype',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
