# Generated by Django 5.2 on 2025-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0006_alter_videotype_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotype',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
