# Generated by Django 5.2 on 2025-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0007_alter_videotype_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoitem',
            old_name='VideoType',
            new_name='itemType',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='itemCategory',
            new_name='newCategory',
        ),
        migrations.AddField(
            model_name='videoitem',
            name='videoPoster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
