# Generated by Django 5.2 on 2025-09-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0008_rename_videotype_videoitem_itemtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoitem',
            old_name='newCategory',
            new_name='itemCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='videotype',
            name='quantity',
        ),
        migrations.AddField(
            model_name='series',
            name='seriesPoster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
    ]
