# Generated by Django 5.2 on 2025-10-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0010_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='videoPoster',
        ),
        migrations.AddField(
            model_name='videoitem',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video_posters/'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='itemCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modrator.category'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='itemType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modrator.videotype'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modrator.series'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
