# Generated by Django 5.2 on 2025-10-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0011_remove_videoitem_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
