# Generated by Django 5.2 on 2025-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0012_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='seriesVideo',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
    ]
