# Generated by Django 5.2 on 2025-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0013_series_seriesvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='seriesPoster',
            field=models.ImageField(blank=True, null=True, upload_to='series_posters/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='seriesVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
