# Generated by Django 5.2 on 2025-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0014_alter_series_seriesposter_alter_series_seriesvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='seriesVideo',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
    ]
