# Generated by Django 5.2 on 2025-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0015_alter_series_seriesvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
