# Generated by Django 5.2.6 on 2025-10-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0016_videoitem_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='thumbnail',
        ),
    ]
