# Generated by Django 5.2.6 on 2025-11-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0017_remove_videoitem_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seriesPoster',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seriesVideo',
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(default='series_images/default.jpg', upload_to='series_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
