# Generated by Django 5.2.6 on 2025-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0018_remove_series_createddate_remove_series_seriesposter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series_images/'),
        ),
    ]
