# Generated by Django 5.2.6 on 2025-11-01 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0019_series_video_alter_series_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='video',
            new_name='seriesVideo',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.RemoveField(
            model_name='series',
            name='year',
        ),
        migrations.AddField(
            model_name='series',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='seriesPoster',
            field=models.ImageField(blank=True, null=True, upload_to='series_posters/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
