# Generated by Django 5.2.6 on 2025-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0020_rename_video_series_seriesvideo_remove_series_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='موقعي', max_length=100)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('dark_mode', models.CharField(choices=[('on', 'تشغيل'), ('off', 'إيقاف')], default='off', max_length=10)),
                ('site_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
