# Generated by Django 5.2.6 on 2025-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0021_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
    ]
