# Generated by Django 5.2.6 on 2026-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0023_remove_movie_poster_remove_series_seriesvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='createdDate',
        ),
        migrations.AddField(
            model_name='series',
            name='seriesVideo',
            field=models.FileField(blank=True, null=True, upload_to='series_videos/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
