# Generated by Django 5.2.6 on 2026-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modrator', '0024_remove_series_createddate_series_seriesvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='itemCategory',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='itemType',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='series',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='video',
        ),
        migrations.AddField(
            model_name='videoitem',
            name='video_file',
            field=models.FileField(default=1, upload_to='video_files/', verbose_name='Video File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='poster',
            field=models.ImageField(upload_to='video_posters/', verbose_name='Video Poster'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer URL (Optional)'),
        ),
    ]
